### PR TITLE
Fixed #464 Better exception if the DynamicConfigurationService was not found

### LINKED ISSUE #464: AbstractModulesRegistryImpl throws NPE without a message
NPE without a message is always bug.
The NPE is present in current payara-minimal maven build and says nothing about the cause. 
This exception is recurring with nearly every update even in other modules and gives no clue what to do.

Target of this issue: better throw IllegalStateException with a message.

### PR DESCRIPTION
**Pull request by dmatej**
- also some formatting and reorganized imports
- exception with a message is better than NPE

Signed-off-by: David Matejcek <dmatej@seznam.cz>

### CODE REVIEW

File: hk2-core/src/main/java/com/sun/enterprise/module/common_impl/AbstractModulesRegistryImpl.java [hunk 1]
```diff
@@ -107,40 +107,43 @@ protected AbstractModulesRegistryImpl(ModulesRegistry parent) {
...
+            config.addActiveDescriptor(DuplicatePostProcessor.class);
+        }
         config.commit();
     }
 
+    private <T> T getServiceOrFail(ServiceLocator serviceLocator, Class<T> contractOrImpl) {
+        final T service = serviceLocator.getService(contractOrImpl);
+        if (service == null) {
+            throw new IllegalStateException("The service '" + contractOrImpl.getName()
+                + "' could not be located byt the locator '" + serviceLocator + "'!");
```
Comment (arjantijms) [inline hk2-core/src/main/java/com/sun/enterprise/module/common_impl/AbstractModulesRegistryImpl.java]: > could not be located byt the locator

Typo ;)

Comment (dmatej) [reply hk2-core/src/main/java/com/sun/enterprise/module/common_impl/AbstractModulesRegistryImpl.java]: Fixed

**Comment by dmatej** [comment]
I think it is not good idea to write test for replacing NPE with ISE. This is not a feature, only a better way to crash and tell something.
Generally I agree there should be tests for these situations, but in another more systematic issue, perhaps with own runtime exception. I think I have seen more places in the code where it would be suitable. This is stacktrace before the change:
```
[INFO] --- glassfishbuild-maven-plugin:3.2.20.payara-p1:exec (create-domain) @ payara-minimal ---
[INFO] executable: /home/dmatej/work/repo/git/Payara/nucleus/distributions/payara-minimal/target/stage/nucleus/bin/nadmin
[INFO] commandLineArgs: --user admin create-domain --nopassword --savelogin=true --checkports=false --portbase=5000 --keytooloptions CN=localhost domain1
[INFO] [exec] Exception in thread "main" java.lang.NullPointerException
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
[INFO] [exec]   at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
[INFO] [exec]   at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:212)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:244)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:238)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:362)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.main(AdminMain.java:206)
```
